# Generated by Django 4.1.7 on 2023-04-04 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_dollars', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_field', models.CharField(max_length=50)),
                ('email_field', models.EmailField(max_length=254)),
                ('password_field', models.CharField(max_length=50)),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto.userdata')),
            ],
        ),
    ]
