# Generated by Django 4.1.7 on 2023-04-17 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_userdata_login_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='login_field',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_field',
        ),
        migrations.RemoveField(
            model_name='user',
            name='login_field',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_field',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crypto.userdata'),
        ),
    ]
