# Generated by Django 4.1.7 on 2023-06-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0005_user_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='wallet_bit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='wallet_dollars',
            field=models.FloatField(default=1000.0),
        ),
    ]
