# Generated by Django 4.1.7 on 2023-06-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0006_alter_userdata_wallet_bit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='wallet_balance',
            field=models.FloatField(default=-1000.0),
        ),
    ]
