# Generated by Django 4.1.7 on 2023-06-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0007_userdata_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='wallet_balance',
            field=models.FloatField(default=0),
        ),
    ]
